// Geographic, Historical and Cultural reference knowledge base
// For biblical/theological educational content

export interface GeoRef {
  id: string;
  names: string[];           // All recognized name variants
  type: 'cidade' | 'regiao' | 'pais' | 'rio' | 'mar' | 'montanha' | 'deserto' | 'império' | 'reino' | 'monumento' | 'povo' | 'personagem' | 'sítio_arqueológico';
  fullName: string;
  location?: string;
  coordinates?: { lat: number; lng: number };
  summary: string;
  biblicalImportance?: string;
  period?: string;
  image?: string;            // Wikimedia Commons URL
  wikiUrl?: string;
}

// =====================================================
// CIDADES BÍBLICAS E HISTÓRICAS
// =====================================================
export const GEO_REFERENCES: GeoRef[] = [
  // === CIDADES ===
  {
    id: 'jerusalem', names: ['Jerusalém', 'Jerusalem', 'Yerushalayim', 'jebus'],
    type: 'cidade', fullName: 'Jerusalém',
    location: 'Israel/Palestina',
    coordinates: { lat: 31.7683, lng: 35.2137 },
    summary: 'Uma das cidades mais antigas do mundo habitado, centro religioso do Judaísmo, Cristianismo e Islamismo. Fundada por volta de 3000 a.C., foi capital do Reino de Israel sob os reis Davi e Salomão.',
    biblicalImportance: 'Capital do Reino de Israel sob Davi e Salomão. Local do Templo de Salomão e do Templo de Herodes. Local da crucificação e ressurreição de Jesus.',
    period: 'Cerca de 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Jerusalem_Dome_of_the_rock_BW_14.JPG/320px-Jerusalem_Dome_of_the_rock_BW_14.JPG',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Jerusalém',
  },
  {
    id: 'belem', names: ['Belém', 'Belem', 'Betlehem', 'Beit Lahm'],
    type: 'cidade', fullName: 'Belém',
    location: 'Palestina, a 10 km de Jerusalém',
    coordinates: { lat: 31.7054, lng: 35.2078 },
    summary: 'Cidade da tribo de Judá, conhecida como a cidade natal de Davi e de Jesus. Sítio arqueológico com história que remonta ao século IV a.C.',
    biblicalImportance: 'Cidade natal do rei Davi (1 Samuel 16) e local do nascimento de Jesus (Mateus 2:1).',
    period: 'Cerca de 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bethlehem_-_Manger_Square_-_20081223.jpg/320px-Bethlehem_-_Manger_Square_-_20081223.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Belém_(Palestina)',
  },
  {
    id: 'nazare', names: ['Nazaré', 'Nazare', 'Nazareth'],
    type: 'cidade', fullName: 'Nazaré',
    location: 'Israel',
    coordinates: { lat: 32.7022, lng: 35.2979 },
    summary: 'Cidade da Galileia onde Jesus cresceu. Era uma vila pequena e insignificante na época bíblica.',
    biblicalImportance: 'Local da Anunciação (Lucas 1:26-38) e da infância e juventude de Jesus (Mateus 2:23, Lucas 2:51).',
    period: 'Cerca de 100 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Nazareth_-_panoramio.jpg/320px-Nazareth_-_panoramio.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Nazaré',
  },
  {
    id: 'jerico', names: ['Jericó', 'Jerico', 'Aricha'],
    type: 'cidade', fullName: 'Jericó',
    location: 'Vale do Jordão, Cisjordânia',
    coordinates: { lat: 31.8733, lng: 35.4444 },
    summary: 'Uma das cidades habitadas mais antigas do mundo. Estrategicamente localizada no vale do Jordão, foi importante ponto de passagem.',
    biblicalImportance: 'Conquistada por Josué (Josué 6). Jesus curou os cegos Bartimeu (Marcos 10:46) e visitou a casa de Zaqueu (Lucas 19:1-10).',
    period: 'Cerca de 9000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Jericho_Village.jpg/320px-Jericho_Village.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Jericó',
  },
  {
    id: 'cafarnaum', names: ['Cafarnaum', 'Capernaum', 'Kfar Nahum'],
    type: 'cidade', fullName: 'Cafarnaum',
    location: 'Margem norte do Mar da Galileia, Israel',
    coordinates: { lat: 32.8803, lng: 35.5764 },
    summary: 'Vila de pescadores que se tornou o centro do ministério de Jesus na Galileia.',
    biblicalImportance: 'Base de operações de Jesus (Mateus 4:13). Local de muitos milagres, incluindo a cura do servo do centurião (Mateus 8:5-13) e a ressurreição da filha de Jairo (Lucas 8:41-56).',
    period: 'Século I a.C. - século VII d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Capernaum_-_the_Town_of_Jesus.jpg/320px-Capernaum_-_the_Town_of_Jesus.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Cafarnaum',
  },
  {
    id: 'roma', names: ['Roma', 'Rome'],
    type: 'cidade', fullName: 'Roma',
    location: 'Itália',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    summary: 'Capital do Império Romano, maior império da antiguidade. Centro político, cultural e militar do mundo antigo.',
    biblicalImportance: 'Destino da viagem de Paulo (Atos 28). Local da martírio de Pedro e Paulo. Sede do cristianismo primitivo.',
    period: '753 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/320px-Colosseo_2020.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Roma',
  },
  {
    id: 'atenas', names: ['Atenas', 'Athens'],
    type: 'cidade', fullName: 'Atenas',
    location: 'Grécia',
    coordinates: { lat: 37.9838, lng: 23.7275 },
    summary: 'Berço da democracia e da filosofia ocidental. Centro cultural e intelectual do mundo antigo.',
    biblicalImportance: 'Paulo pregou no Areópago (Atos 17:16-34). Cidade visitada por Paulo em sua segunda viagem missionária.',
    period: 'Circa 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camponotus_flavomarginatus_ant.jpg/320px-Camponotus_flavomarginatus_ant.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Atenas',
  },
  {
    id: 'corinto', names: ['Corinto', 'Corinth'],
    type: 'cidade', fullName: 'Corinto',
    location: 'Grécia',
    coordinates: { lat: 37.9409, lng: 22.9295 },
    summary: 'Importante cidade comercial e portuária da Grécia antiga, conhecida por sua riqueza e costumes pagãos.',
    biblicalImportance: 'Paulo fundou igreja em Corinto (Atos 18:1-18). Escreveu as duas cartas aos Coríntios. A igreja era conhecida por seus problemas e pela instrução de Paulo.',
    period: 'Circa 6000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Archaia_Korinthos_01.jpg/320px-Archaia_Korinthos_01.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Corinto',
  },
  {
    id: 'efeso', names: ['Éfeso', 'Efeso', 'Ephesus'],
    type: 'cidade', fullName: 'Éfeso',
    location: 'Turquia (Anatólia)',
    coordinates: { lat: 37.9411, lng: 27.3420 },
    summary: 'Uma das maiores cidades do mundo romano, centro comercial e cultural. Sede de um dos Sete Lugares da Igreja do Apocalipse.',
    biblicalImportance: 'Paulo pregou em Éfeso por três anos (Atos 20:31). A igreja de Éfeso é endereçada no Apocalipse 2:1-7. Marcos, Timóteo e Apolos estiveram na região.',
    period: 'Circa 1000 a.C. - século XV d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ephesus_Celsus_Library_Fa%C3%A7ade.jpg/320px-Ephesus_Celsus_Library_Fa%C3%A7ade.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Éfeso',
  },
  {
    id: 'antonina', names: ['Antioquia', 'Antioch'],
    type: 'cidade', fullName: 'Antioquia',
    location: 'Turquia (atual Antakya)',
    coordinates: { lat: 36.2000, lng: 36.1600 },
    summary: 'Terceira maior cidade do Império Romano, centro comercial e cultural importante.',
    biblicalImportance: 'Centro da igreja primitiva (Atos 11:19-26). Paulo e Barnabé foram enviados daqui (Atos 13:1-3). Os discípulos foram chamados de cristãos pela primeira vez em Antioquia (Atos 11:26).',
    period: 'Circa 300 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Antakya_Harbiye_City_Park_049.jpg/320px-Antakya_Harbiye_City_Park_049.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Antioquia',
  },
  {
    id: 'alexandria', names: ['Alexandria', 'Alexandria'],
    type: 'cidade', fullName: 'Alexandria',
    location: 'Egito',
    coordinates: { lat: 31.2001, lng: 29.9187 },
    summary: 'Fundada por Alexandre Magno em 331 a.C., tornou-se um dos maiores centros intelectuais do mundo antigo, com a famosa Biblioteca de Alexandria.',
    biblicalImportance: 'Filipe pregou em Atos 8:40. Apolos, eloquente nas Escrituras, veio de Alexandria (Atos 18:24).',
    period: '331 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Bibliotheca_Alexandrina_main.jpg/320px-Bibliotheca_Alexandrina_main.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Alexandria',
  },
  {
    id: 'babilonia', names: ['Babilônia', 'Babilonia', 'Babylon', 'Babel'],
    type: 'império', fullName: 'Babilônia',
    location: 'Mesopotâmia (atual Iraque)',
    coordinates: { lat: 32.5363, lng: 44.4209 },
    summary: 'Uma das maiores civilizações da antiguidade, centro de poder, cultura e aprendizado. Capital do Império Neobabilônico sob Nabucodonosor II.',
    biblicalImportance: 'Torre de Babel (Gênesis 11). Captura de Jerusalém e exílio babilônico (2 Reis 25). Grande prostituta do Apocalipse 17-18.',
    period: '2334 a.C. - 539 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Ishtar_gate_at_Pergamon_museum_in_Berlin.jpg/320px-Ishtar_gate_at_Pergamon_museum_in_Berlin.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Babilônia',
  },
  {
    id: 'egito', names: ['Egito', 'Egypt', 'Mizraim'],
    type: 'pais', fullName: 'Egito',
    location: 'Norte da África',
    coordinates: { lat: 26.8206, lng: 30.8025 },
    summary: 'Uma das mais antigas civilizações do mundo, com história que remonta a mais de 5000 anos. Famoso pelas pirâmides, esfinge e pela civilização faraônica.',
    biblicalImportance: 'Abrão, Jacó e os filhos de Israel viviam no Egito. Moisés libertou os israelitas do cativeiro. Jesus foi refugiado no Egito (Mateus 2:14-15).',
    period: 'Circa 3100 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/320px-Kheops-Pyramid.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Egito',
  },
  {
    id: 'mesopotamia', names: ['Mesopotâmia', 'Mesopotamia'],
    type: 'regiao', fullName: 'Mesopotâmia',
    location: 'Entre os rios Tigre e Eufrates (atual Iraque)',
    coordinates: { lat: 33.3128, lng: 44.3615 },
    summary: '"Terra entre os rios" — berço de algumas das primeiras civilizações humanas, incluindo sumérios, acadianos, babilônios e assírios.',
    biblicalImportance: 'Local da Torre de Babel (Gênesis 11). Pátria de Abraão (Gênesis 11:31). Local da queda da Babilônia (Daniel 5).',
    period: 'Circa 5500 a.C. - 539 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Map_of_ancient_Mesopotamia.jpg/320px-Map_of_ancient_Mesopotamia.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Mesopotâmia',
  },
  {
    id: 'rio_jordao', names: ['Rio Jordão', 'Jordão', 'Jordan River', 'Yarden'],
    type: 'rio', fullName: 'Rio Jordão',
    location: 'Oriente Médio, fluxo do Monte Hermon ao Mar Morto',
    coordinates: { lat: 31.8556, lng: 35.5528 },
    summary: 'Rio de aproximadamente 252 km de comprimento, importante na história bíblica como fronteira e local de eventos significativos.',
    biblicalImportance: 'Josué e os israelitas atravessaram o Jordão para entrar na Terra Prometida (Josué 3). Jesus foi batizado por João Batista no Jordão (Mateus 3:13-17).',
    period: 'Circa 10000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Jordan_River_near_Jericho.jpg/320px-Jordan_River_near_Jericho.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Rio_Jordão',
  },
  {
    id: 'mar_morto', names: ['Mar Morto', 'Dead Sea', 'Mar Salgado'],
    type: 'mar', fullName: 'Mar Morto',
    location: 'Fronteira Israel-Jordânia',
    coordinates: { lat: 31.5000, lng: 35.5000 },
    summary: 'O ponto mais baixo da superfície terrestre (-430 metros). Água extremamente salina, impossível sustentar vida aquática.',
    biblicalImportance: 'Associado à destruição de Sodoma e Gomorra (Gênesis 19). David refugiou-se nesta região (1 Samuel 23:29).',
    period: 'Circa 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Dead_Sea_Mud_Beach.jpg/320px-Dead_Sea_Mud_Beach.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Mar_Morto',
  },
  {
    id: 'mar_galileia', names: ['Mar da Galileia', 'Lago de Genesaré', 'Mar de Tiberíades', 'Sea of Galilee'],
    type: 'mar', fullName: 'Mar da Galileia',
    location: 'Norte de Israel',
    coordinates: { lat: 32.8333, lng: 35.5833 },
    summary: 'Lago de água doce de aproximadamente 53 km de circunferência, importante para a pesca e o comércio na época bíblica.',
    biblicalImportance: 'Jesus caminhou sobre as águas (Mateus 14:22-33). Multiplicou pães e peixes (Mateus 14:13-21). Chamou seus primeiros discípulos (Mateus 4:18-22).',
    period: 'Circa 10000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Sea_of_Galilee_%28Tiberias%29.jpg/320px-Sea_of_Galilee_%28Tiberias%29.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Mar_da_Galileia',
  },
  {
    id: 'monte_sinai', names: ['Monte Sinai', 'Sinai', 'Horeb'],
    type: 'montanha', fullName: 'Monte Sinai',
    location: 'Península do Sinai, Egito',
    coordinates: { lat: 28.5389, lng: 33.9754 },
    summary: 'Montanha de aproximadamente 2.285 metros de altura, local sagrado no judaísmo, cristianismo e islamismo.',
    biblicalImportance: 'Local onde Moisés recebeu os Dez Mandamentos (Êxodo 19-20). Deus falou com Moisés na sarça ardente (Êxodo 3:1-6).',
    period: 'Circa 1400 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Mount_Sinai_in_Egypt.jpg/320px-Mount_Sinai_in_Egypt.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Monte_Sinai',
  },
  {
    id: 'monte_carmelo', names: ['Monte Carmelo', 'Carmelo', 'Mount Carmel'],
    type: 'montanha', fullName: 'Monte Carmelo',
    location: 'Norte de Israel, perto de Haifa',
    coordinates: { lat: 32.7397, lng: 35.0336 },
    summary: 'Cadeia montanhosa costeira de aproximadamente 39 km, com vistas para o Vale de Jezreel e o Mar Mediterrâneo.',
    biblicalImportance: 'Local onde Elias confrontou os profetas de Baal (1 Reis 18:20-40). Referido como "Karmel" nos livros proféticos.',
    period: 'Circa 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Mount_Carmel_from_the_Mediterranean.jpg/320px-Mount_Carmel_from_the_Mediterranean.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Monte_Carmelo',
  },
  {
    id: 'deserto_sina', names: ['Deserto do Sinai', 'Deserto de Sin', 'Sinai Desert'],
    type: 'deserto', fullName: 'Deserto do Sinai',
    location: 'Península do Sinai, entre Egito e Israel',
    coordinates: { lat: 29.5000, lng: 34.0000 },
    summary: 'Deserto de pedra e areia, com temperaturas extremas. Local de peregrinação e reflexão espiritual.',
    biblicalImportance: 'Local onde os israelitas vagaram por 40 anos após o Êxodo (Números 14:33-34). Jesus foi tentado aqui (Mateus 4:1).',
    period: 'Circa 1400 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Sinai_Mountain.jpg/320px-Sinai_Mountain.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Deserto_do_Sinai',
  },
  {
    id: 'qumran', names: ['Qumran', 'Kumran'],
    type: 'sítio_arqueológico', fullName: 'Qumran',
    location: 'Margem noroeste do Mar Morto',
    coordinates: { lat: 31.7414, lng: 35.4578 },
    summary: 'Sítio arqueológico onde foram encontrados os Manuscritos do Mar Morto, os manuscritos mais antigos da Bíblia hebraica.',
    biblicalImportance: 'Casa dosEssênios, seita judaica que preparava o caminho para o messias. Os manuscritos incluem cópias de quase todos os livros do Antigo Testamento.',
    period: 'Circa 150 a.C. - 68 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Qumran_-_the_Settlement.jpg/320px-Qumran_-_the_Settlement.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Qumran',
  },
  {
    id: 'massada', names: ['Massada', 'Masada'],
    type: 'sítio_arqueológico', fullName: 'Massada',
    location: 'Margem sudeste do Mar Morto',
    coordinates: { lat: 31.3156, lng: 35.3536 },
    summary: 'Fortaleza construída por Herodes, o Grande. Local do último reduto dos rebeldes judeus contra Roma em 73 d.C.',
    biblicalImportance: 'Embora não mencionada diretamente na Bíblia, é um símbolo do resistência judaica e da destruição de Jerusalém em 70 d.C.',
    period: 'Circa 37 a.C. - 73 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Massada_by_David_Shankbone.jpg/320px-Massada_by_David_Shankbone.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Massada',
  },
  {
    id: 'templo_salomao', names: ['Templo de Salomão', 'Primeiro Templo'],
    type: 'monumento', fullName: 'Templo de Salomão',
    location: 'Monte do Templo, Jerusalém',
    coordinates: { lat: 31.7833, lng: 35.2333 },
    summary: 'Primeiro templo em Jerusalém, construído por Salomão por volta de 957 a.C. Destruído pelos babilônios em 586 a.C.',
    biblicalImportance: 'Local central do culto israelita. Construído seguindo instruções divinas transmitidas a Davi e Salomão (1 Reis 6-7).',
    period: 'Circa 957 a.C. - 586 a.C.',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Templo_de_Salomão',
  },
  {
    id: 'templo_herodes', names: ['Templo de Herodes', 'Segundo Templo'],
    type: 'monumento', fullName: 'Templo de Herodes',
    location: 'Monte do Templo, Jerusalém',
    coordinates: { lat: 31.7833, lng: 35.2333 },
    summary: 'Reconstrução grandiosa do Segundo Templo por Herodes, o Grande. Uma das mais magníficas construções do mundo antigo.',
    biblicalImportance: 'Jesus ensinou e purificou o templo (Mateus 21:12-13). Local onde Simeão reconheceu o Messias (Lucas 2:25-35). Destruído em 70 d.C.',
    period: 'Circa 20 a.C. - 70 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Second_Temple_Model.jpg/320px-Second_Temple_Model.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Templo_de_Herodes',
  },
  // === PESSOAS HISTÓRICAS ===
  {
    id: 'davi', names: ['Davi', 'David'],
    type: 'personagem', fullName: 'Davi',
    location: 'Reino de Israel',
    summary: 'Segundo rei de Israel, considerado o maior rei da história israelita. Poeta, guerreiro e ancestor de Jesus.',
    biblicalImportance: 'Matou Golias (1 Samuel 17). Uniu as tribos de Israel. Estabeleceu Jerusalém como capital. Ancestral de Jesus (Mateus 1:1).',
    period: 'Circa 1040-970 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Michelangelo_-_David_3.jpg/320px-Michelangelo_-_David_3.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Davi',
  },
  {
    id: 'salomao', names: ['Salomão', 'Solomon'],
    type: 'personagem', fullName: 'Salomão',
    location: 'Reino de Israel',
    summary: 'Terceiro rei de Israel, filho de Davi. Conhecido por sua sabedoria, riqueza e construção do Templo.',
    biblicalImportance: 'Construiu o Templo de Jerusalém (1 Reis 6-7). Conhecido pela Sabedoria de Salomão (Provérbios, Eclesiastes, Cantares).',
    period: 'Circa 990-931 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Solomon_and_the_Queen_of_Sheba.jpg/320px-Solomon_and_the_Queen_of_Sheba.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Salomão',
  },
  {
    id: 'abrahao', names: ['Abraão', 'Abraham'],
    type: 'personagem', fullName: 'Abraão',
    location: 'Caldéia → Canaã → Egito',
    summary: 'Patriarca do judaísmo, cristianismo e islamismo. Considerado o pai da fé.',
    biblicalImportance: 'Chamado por Deus para ir à terra que lhe seria mostrada (Gênesis 12:1-3). Pai da promessa. ancestral de Israel e de Jesus.',
    period: 'Circa 2000 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Abraham_and_the_Three_Angels.jpg/320px-Abraham_and_the_Three_Angels.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Abraão',
  },
  {
    id: 'moises', names: ['Moisés', 'Moses'],
    type: 'personagem', fullName: 'Moisés',
    location: 'Egito → Deserto do Sinai',
    summary: 'Líder dos israelitas no Êxodo, legislador e profeta. Autor tradicional dos cinco primeiros livros da Bíblia.',
    biblicalImportance: 'Liberou os israelitas do cativeiro egípcio. Recebeu os Dez Mandamentos no Sinai. Liderou o povo pelo deserto por 40 anos.',
    period: 'Circa 1526-1406 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Charpentier-Moses-with-the-Ten-Commandments-1684.jpg/320px-Charpentier-Moses-with-the-Ten-Commandments-1684.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Moisés',
  },
  {
    id: 'elias', names: ['Elias', 'Elijah'],
    type: 'personagem', fullName: 'Elias',
    location: 'Reino do Norte (Israel)',
    summary: 'Profeta do século IX a.C., conhecido por confrontar a idolatria e por ser levado ao céu em um carro de fogo.',
    biblicalImportance: 'Confrontou os profetas de Baal no Monte Carmelo (1 Reis 18). Foi levado ao céu sem morrer (2 Reis 2:11). Apareceu com Moisés na transfiguração de Jesus.',
    period: 'Circa 900 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Murillo_Elijah_in_the_Fiery_Chariot.jpg/320px-Murillo_Elijah_in_the_Fiery_Chariot.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Elias',
  },
  {
    id: 'paulo', names: ['Paulo', 'Paul', 'Saulo de Tarso'],
    type: 'personagem', fullName: 'Paulo (Saulo de Tarso)',
    location: 'Império Romano',
    summary: 'Apóstolo dos gentios, autor de 13 epístolas no Novo Testamento. Perseguiu cristãos antes de sua conversão.',
    biblicalImportance: 'Conversão no caminho de Damasco (Atos 9). Realizou três viagens missionárias. Escreveu a maioria das epístolas do Novo Testamento.',
    period: 'Circa 5-67 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Caravaggio_-_Conversion_of_Saint_Paul.jpg/320px-Caravaggio_-_Conversion_of_Saint_Paul.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Paulo_de_Tarso',
  },
  {
    id: 'pedro', names: ['Pedro', 'Peter', 'Simão Pedro'],
    type: 'personagem', fullName: 'Pedro (Simão)',
    location: 'Galileia → Jerusalém → Roma',
    summary: 'Um dos doze apóstolos de Jesus, considerado o líder da igreja primitiva.',
    biblicalImportance: 'Primeiro a declarar Jesus como Messias (Mateus 16:16). Pregou no Pentecostes (Atos 2). Escreveu duas epístolas.',
    period: 'Circa 1-67 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Peter_and_Paul.jpg/320px-Peter_and_Paul.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Simão_Pedro',
  },
  // === IMÉRIOS E REINOS ===
  {
    id: 'imperio_romano', names: ['Império Romano', 'Rome', 'Roma'],
    type: 'império', fullName: 'Império Romano',
    location: 'Europa, Ásia Menor, Norte da África',
    summary: 'Um dos maiores impérios da história, governando a maior parte do mundo conhecido por séculos.',
    biblicalImportance: 'Governava Israel no tempo de Jesus. Jesus foi crucificado sob autoridade romana. Paulo foi cidadão romano.',
    period: '27 a.C. - 476 d.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Imperium_Romanum.svg/320px-Imperium_Romanum.svg.png',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Império_Romano',
  },
  {
    id: 'imperio_babilonico', names: ['Império Babilônico', 'Babilônia'],
    type: 'império', fullName: 'Império Babilônico',
    location: 'Mesopotâmia',
    summary: 'Império que dominou o Oriente Médio por séculos, especialmente sob Nabucodonosor II.',
    biblicalImportance: 'Destruiu Jerusalém e o Templo em 586 a.C. Capturou e exilou o povo de Judá. Nabucodonosor é mencionado em Daniel.',
    period: '1894-539 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Ishtar_gate_at_Pergamon_museum_in_Berlin.jpg/320px-Ishtar_gate_at_Pergamon_museum_in_Berlin.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Império_Babilônico',
  },
  {
    id: 'imperio_assirio', names: ['Império Assírio', 'Assíria'],
    type: 'império', fullName: 'Império Assírio',
    location: 'Mesopotâmia (norte)',
    summary: 'Império militarista conhecido por sua crueldade e eficiência administrativa.',
    biblicalImportance: 'Destruiu o Reino do Norte (Israel) em 722 a.C. Senaqueribe cercou Jerusalém (2 Reis 19).',
    period: '2500-609 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Nineveh_600_B.C.png/320px-Nineveh_600_B.C.png',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Império_Assírio',
  },
  {
    id: 'imperio_persa', names: ['Império Persa', 'Pérsia'],
    type: 'império', fullName: 'Império Persa (Aquemênida)',
    location: 'Oriente Médio, Ásia Central',
    summary: 'Maior império da antiguidade, conhecido por sua tolerância religiosa e administração eficiente.',
    biblicalImportance: 'Ciro, o Grande, libertou os judeus do exílio babilônico (Esdras 1:1-4). Artaxerxes permitiu a reconstrução de Jerusalém (Neemias 2).',
    period: '550-330 a.C.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Persepolis_24.11.2009_11-12-14.jpg/320px-Persepolis_24.11.2009_11-12-14.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Império_Persa',
  },
  // === POVOS ANTIGOS ===
  {
    id: 'hebreus', names: ['Hebreus', 'Israelitas', 'Filhos de Israel'],
    type: 'povo', fullName: 'Hebreus/Israelitas',
    location: 'Canaã → Egito → Canaã',
    summary: 'Povo semita descendente de Abraão, Isaac e Jacó. Formaram as doze tribos de Israel.',
    biblicalImportance: 'Escolhidos por Deus como seu povo. Receberam a Lei no Sinai. Entraram na Terra Prometida sob Josué.',
    period: 'Circa 2000 a.C. - 70 d.C.',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Hebreus',
  },
  {
    id: 'filisteus', names: ['Filisteus', 'Philistines'],
    type: 'povo', fullName: 'Filisteus',
    location: 'Costa de Canaã (atual Faixa de Gaza)',
    summary: 'Povo marítimo que se estabeleceu na costa de Canaã. Inimigos constantes dos israelitas.',
    biblicalImportance: 'Golias, o gigante, era filisteu (1 Samuel 17). Sansão lutou contra filisteus (Juízes 14-16).',
    period: 'Circa 1175-600 a.C.',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Filisteus',
  },
  {
    id: 'samartianos', names: ['Samaritanos', 'Samaritanos'],
    type: 'povo', fullName: 'Samaritanos',
    location: 'Região de Samaria, Palestina',
    summary: 'Grupo étnico-religioso que descendente de israelitas misturados com outros povos. Mantêm uma versão própria do Torá.',
    biblicalImportance: 'Jesus conversou com a mulher samaritana (João 4). Parábola do Bom Samaritano (Lucas 10:30-37).',
    period: 'Circa 722 a.C. - presente',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Samaritanos',
  },
  // === RIOS E MARES ===
  {
    id: 'eufrates', names: ['Eufrates', 'Euphrates'],
    type: 'rio', fullName: 'Rio Eufrates',
    location: 'Oriente Médio (Turquia, Síria, Iraque)',
    coordinates: { lat: 31.0000, lng: 47.0000 },
    summary: 'Um dos dois rios da Mesopotâmia (com o Tigre), com 2.800 km de comprimento. Fundamental para as civilizações da região.',
    biblicalImportance: 'Um dos quatro rios do Éden (Gênesis 2:14). Fronteira oriental da Terra Prometida (Josué 1:4).',
    period: 'Circa 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Euphrates_River_near_Habbaniyah.jpg/320px-Euphrates_River_near_Habbaniyah.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Eufrates',
  },
  {
    id: 'tigre', names: ['Tigre', 'Tigris'],
    type: 'rio', fullName: 'Rio Tigre',
    location: 'Oriente Médio (Turquia, Síria, Iraque)',
    coordinates: { lat: 31.0000, lng: 46.0000 },
    summary: 'Um dos dois rios principais da Mesopotâmia, com 1.900 km de comprimento.',
    biblicalImportance: 'Um dos quatro rios do Éden (Gênesis 2:14).',
    period: 'Circa 3000 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Tigris_River_in_Turkey.jpg/320px-Tigris_River_in_Turkey.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Tigre_(rio)',
  },
  {
    id: 'nilo', names: ['Nilo', 'Nile'],
    type: 'rio', fullName: 'Rio Nilo',
    location: 'África (11 países)',
    coordinates: { lat: 26.0000, lng: 31.0000 },
    summary: 'Rio mais longo da África (6.650 km), fundamental para a civilização egípcia.',
    biblicalImportance: 'Associado ao Egito bíblico. Moisés foi colocado no Nilo (Êxodo 2:3). As pragas do Egito incluíram transformação do Nilo em sangue.',
    period: 'Circa 3100 a.C. - presente',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Luxor_and_the_Nile.jpg/320px-Luxor_and_the_Nile.jpg',
    wikiUrl: 'https://pt.wikipedia.org/wiki/Nilo',
  },
];

/**
 * Find matching references in text
 */
export function findGeoReferences(text: string): Array<{ ref: GeoRef; match: string; index: number }> {
  const results: Array<{ ref: GeoRef; match: string; index: number }> = [];
  const seen = new Set<string>();

  for (const ref of GEO_REFERENCES) {
    for (const name of ref.names) {
      // Use word boundary matching to avoid false positives
      const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const regex = new RegExp(`(?<![a-zA-Záàâãéèêíïóôõúüçñ])${escaped}(?![a-zA-Záàâãéèêíïóôõúüçñ])`, 'gi');
      
      let match;
      while ((match = regex.exec(text)) !== null) {
        const key = `${ref.id}:${match.index}`;
        if (!seen.has(key)) {
          seen.add(key);
          results.push({ ref, match: match[0], index: match.index });
        }
      }
    }
  }

  return results.sort((a, b) => a.index - b.index);
}
